export const START_APP = "START_APP";
export const START_APP_FULFILLED = `${START_APP}_FULFILLED`;
export const START_APP_PENDING = `${START_APP}_PENDING`;

export const PLAYER__SAVE = "PLAYER__SAVE";
export const PLAYER__SAVE_FULFILLED = `${PLAYER__SAVE}_FULFILLED`;
export const PLAYER__SAVE_PENDING = `${PLAYER__SAVE}_PENDING`;
